### ISSUE TITLE
Binary availability (or build instructions)

### ISSUE THREAD

**Issue by ghost** [MagerValp/ArcadeGameSelector#1]
Is it possible to download a binary rather than source code? Or if not, could you provide build instructions? I've never compiled anything on Amiga - I've no idea how to do it (although I've used make on linux). 

Thank you. This looks amazing.

**Comment by MagerValp** [comment]
Binaries have been posted in the EAB discussion thread: http://eab.abime.net/showthread.php?t=68818

I added links in the readme.
