### ISSUE TITLE
Sorting is not case insensitive

### ISSUE THREAD

**Issue by limi** [MagerValp/ArcadeGameSelector#12]
For example, "SWIV" is sorted before "Sensible Soccer".

**Comment by Optiroc** [comment]
I've wanted this too. Let's!

**Comment by Optiroc** [comment]
Done. I'm sure there's a better way to implement a [CHAR] lookup table, though. Committing tomorrow, after some deliberation.

**Comment by Optiroc** [comment]
Implemented in e4224602a92642be4f528103df83b1e2d519fd0c.
