### ISSUE TITLE
Cycle through multiple screenshots per game

### ISSUE THREAD

**Issue by limi** [MagerValp/ArcadeGameSelector#13]
As part of the upgrade to the MegaAGS script, we started thinking of how we could improve the launcher even further.

The first thing that came to mind for me was to add the ability for the screenshot section of the page to cycle/fade between multiple screenshots for a given game — not a screenshot browser or anything, just a `game-screenshot-1.iff` → `game-2game-screenshot-1.iff` and then from the start again with e.g. a 3 second delay.

The problem this solves is that many games have great and memorable title screens, but just showing those isn't very representative of the game itself. There are also games that have multiple major parts, e.g. a shooter stage and a platform stage, and it would be great to show both when you're looking at a game.

Of course, care needs to be taken for performance here, I think lazy loading of the non-primary screenshot in the background when viewing an item can get it ready by the time it fades in the next image, etc.

**Comment by Optiroc** [comment]
Implemented in 2e89b494640c91dc9fcf7a0ac1a11f72fdb92718

Thanks @Stat-Mat!
