### ISSUE TITLE
Screenshots with variable size corrupts the display

### ISSUE THREAD

**Issue by limi** [MagerValp/ArcadeGameSelector#14]
When building a launcher with screenshots that have variable sizes (e.g. 200px NTSC & 256px PAL, various overscan sizes), the display gets corrupted when flipping between the entries. Test case attached.

[Variable screenshot size test.zip](https://github.com/MagerValp/ArcadeGameSelector/files/6088426/Variable.screenshot.size.test.zip)

**Comment by limi** [comment]
(Note that this isn’t really an issue for me in the sense that I can standardize the images by adding black borders, but wanted to mention it as something that caused me issues until I understood what was going on)

**Comment by Stat-Mat** [comment]
Given that it's probably best to standardise a set of images for use in AGS2 when building a collection, do we still think the code should try to work with mixed resolution images? I mean, even with the bug fixed, it looks a bit odd placing the top left hand corner of the image at the screenshot X and Y coords, as images won't always look centrally placed in the area the skin designer has left blank. Of course code could be added to handle this (i.e. place centrally in a predefined area), but that would add extra processing to the native code.

My new enhancement to support the screenshot slideshow has also optimised the handling images to improve performance, including the removal of the code which reallocs the bitmap and raster objects every time a new image is displayed, by allocating only once based on the properties of the first image loaded, although of course this will only work if all screenshots are standard size and depth. What do you guys think? Of course, I can easily continue to support mixed resolution images and fix the bug in my upcoming pull request, but maybe it would be better to drop it anyway? Would just like to know what you guys think. ;)

**Comment by Optiroc** [comment]
@Stat-Mat Getting rid of re-alloc on each image load sounds 👍 . But how about only re-allocating memory if the image to be decoded is larger than the currently allocated buffer?

**Comment by Stat-Mat** [comment]
@Optiroc indeed, I had been thinking very much the same thing after posting my update. I will implement it so that it only re-allocs if the image size changes (which of course can be avoided by using a standardised image resolution), as well as incorporate the fix for the variable size image corruption.

**Comment by Optiroc** [comment]
Fixed in 2e89b494640c91dc9fcf7a0ac1a11f72fdb92718

Thanks @Stat-Mat!
