### ISSUE TITLE
Can you use this with AGS 1.0

### ISSUE THREAD

**Issue by CommodoreOS** [MagerValp/ArcadeGameSelector#16]
Can I use the start files from it or will I have to make them, I got AGS 1.0 from the Amiga CD32 Compilation CD that was made by Gary in 2003, I copied the files from it to a hdf file and fixed it in WinUAE so I could load it in Retroarch (P-UAE) in my THEC64 Maxi, it a hack I made for THEC64 called PCUAE.

**Comment by CommodoreOS** [comment]
Iff image files from AGS 1.0 do not display properly in AGS2, the colours on the images are like a negative..?

**Comment by Vecinagamer** [comment]
Could you make an Ags2 of up to 2 gb .hdf for psvita please...
I had an ags2 up to 2 gb but my sister has erased my micro sd, please.
