### ISSUE TITLE
NTSC support?

### ISSUE THREAD

**Issue by Televicious** [MagerValp/ArcadeGameSelector#5]
I can't find any setting to use AGS2 with NTSC. It crashes out on trying to load the display. is there a way to get it to work? Thanks

**Comment by MagerValp** [comment]
With a mode of e.g. `$19000` and an appropriately sized background image, it should just work. If it crashes that's of course a bug, but you'll have to give me a more detailed bug description.

**Comment by Televicious** [comment]
Ok thanks, I'll try that mode. It would just say can't display at restart
the machine.

**Comment by Televicious** [comment]
I couldn't find anything in settings to change a mode with that value. I
actually don't have any background image set so it loads in PAL with just
black background. The error message it gives after the boot menu is
'couldn't open screen' and then it kicks out to workbench. Wondering if I
have to reinstall completely in ntsc mode on winuae. I'm using this on a
MiST FPGA system. Anyhow, guess I'll just use PAL mode until I figure it
out. Thanks.

**Comment by Televicious** [comment]
So I tried building an image in NTSC mode on UAE tried AGS2 on there and it has the same error. Unless I'm doing something wrong it doesn't seem to be compatible. The whdload games work generally for the most part from workbench and other menu systems.

**Comment by Optiroc** [comment]
I've been using AGS2 with MiSTer/Minimig set up as an NTSC machine for a while now without issues. Make sure you have both PAL and NTSC drivers in DEVS:Monitors.

**Comment by HVR88** [comment]
Necro post.  It only crashes when launched from Amiga Boot Selector. If opened from Workbench directly or from a script (such as installed by hstWB), it works fine in NTSC.
