### ISSUE TITLE
AGS does not release file locks

### ISSUE THREAD

**Issue by limi** [MagerValp/ArcadeGameSelector#7]
Steps to reproduce:

1. Launch AGS
2. Quit AGS
3. Try to delete a .txt file used by the menu from the file system

The OS will now complain that the file is in use, and you need to reboot if you want to delete the file.

Obviously not a huge issue, but a bit annoying when you’re working on setting up the files and testing your setup. 😊

**Comment by limi** [comment]
It only happens for the .txt files, by the way — the .run/.iff files can be deleted and are not locked.

**Comment by Optiroc** [comment]
I tried to fix this issue about a year ago, but only took a quick stab at it really. I wasn't able to release the file locks without crashing the app unfortunately.

**Comment by MagerValp** [comment]
It seems like I simply forgot to Close after Open, doesn't `IF fh THEN Close(fh)` in the `EXCEPT DO` block work?

I need to get my dev environment up and running again...

**Comment by Optiroc** [comment]
I’ll give it another try tonight, or thereabouts. :)

**Comment by Optiroc** [comment]
Maybe I double free'd the handle with my previous fix (which is strange since I did the null-check in both places). Only freeing in th except-block seems to work as expected.

Currently I based the fix off my copy which I forgot had another feature already merged. PR:d that first. 🤗

**Comment by MagerValp** [comment]
@limi Can you try the build @Optiroc posted in the PR?

**Comment by limi** [comment]
Seems to work 😊
