### ISSUE TITLE
Handle using 320×2xx images in 640×2xx resolutions

### ISSUE THREAD

**Issue by limi** [MagerValp/ArcadeGameSelector#9]
Most game screenshots will be 320x200, whereas you probably want 640x256 (or 640x200) for your games launcher.

At the moment, I have to pixel-double every single image I want to use from 320x200 to 640x200 (using the full-size style graphics setup included in the AGS2 defaults).

Would be nice if it could automatically do this, since computers are less error prone than me doing it manually. 😄

**Comment by MagerValp** [comment]
Since images have to have their palette remapped, I've put aspect ratio correction and integer scaling in my conversion scripts. Putting live scaling in the menu doesn't seem like a good idea, but a dedicated batch conversion tool would be really nice, with Spacial Color Quantization for OCS.

**Comment by limi** [comment]
Fair enough, I’m probably assuming 680x0 is a lot faster than it actually is. 😄 

If we could get a dedicated script (that isn’t attempting to use Pillow 😂), that would be great, and solve the problem.
